//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.TramitesDigitales2016.Modelos.Contextos
{
    using System;
    
    public partial class pa_PeticionesWeb_TableroControl_Obtener_Peticiones_Result1
    {
        public Nullable<long> No { get; set; }
        public int IdPeticion { get; set; }
        public string Folio { get; set; }
        public string Curp { get; set; }
        public string TipoPeticion { get; set; }
        public string Solicitante { get; set; }
        public string Delegacion { get; set; }
        public System.DateTime AvisoRecepcion { get; set; }
        public Nullable<System.DateTime> RespuestaDelegado { get; set; }
        public Nullable<int> DiasRespuestaDelegado { get; set; }
        public Nullable<int> IdSemaforoRespuestaDelegado { get; set; }
        public string HexadecimalSemaforoRespuestaDelegado { get; set; }
        public string ColorSemaforoRespuestaDelegado { get; set; }
        public Nullable<System.DateTime> TurnadoPeticion { get; set; }
        public Nullable<int> DiasTurnadoPeticion { get; set; }
        public Nullable<int> IdSemaforoTurnadoPeticion { get; set; }
        public string HexadecimalSemaforoTurnadoPeticion { get; set; }
        public string ColorSemaforoTurnadoPeticion { get; set; }
        public Nullable<System.DateTime> RespuestaOpe { get; set; }
        public Nullable<int> DiasRespuestaOpe { get; set; }
        public Nullable<int> IdSemaforoRespuestaOpe { get; set; }
        public string HexadecimalSemaforoRespuestaOpe { get; set; }
        public string ColorSemaforoRespuestaOpe { get; set; }
        public Nullable<int> DiasTotales { get; set; }
        public string EstatusGeneralTramite { get; set; }
    }
}
