//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.TramitesDigitales2016.Modelos.Contextos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Lada { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoMovil { get; set; }
        public string Red { get; set; }
        public string CorreoElectronico { get; set; }
        public string Clave { get; set; }
        public int IdEnlace { get; set; }
        public int IdTipoUsuario { get; set; }
        public string EstatusRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuarioRegistro { get; set; }
    }
}
