//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2015.Common.Reports.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISSSTE.Tramites2015.Common.Reports.Resources.ReportValues", typeof(ReportValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultEmptyProcedureStatus {
            get {
                return ResourceManager.GetString("DefaultEmptyProcedureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de los tiempos.
        /// </summary>
        internal static string DefaultEndDate {
            get {
                return ResourceManager.GetString("DefaultEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen de los tiempos.
        /// </summary>
        internal static string DefaultStartDate {
            get {
                return ResourceManager.GetString("DefaultStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lodgment.
        /// </summary>
        internal static string LodgmentTypeFormat {
            get {
                return ResourceManager.GetString("LodgmentTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string NameSubreportFooter {
            get {
                return ResourceManager.GetString("NameSubreportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string NameSubreportHeader {
            get {
                return ResourceManager.GetString("NameSubreportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LodgmentData.
        /// </summary>
        internal static string NameSubreportLodgmentData {
            get {
                return ResourceManager.GetString("NameSubreportLodgmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LodgmentPerson.
        /// </summary>
        internal static string NameSubreportLodgmentPerson {
            get {
                return ResourceManager.GetString("NameSubreportLodgmentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageData.
        /// </summary>
        internal static string NameSubreportPackgeData {
            get {
                return ResourceManager.GetString("NameSubreportPackgeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackagePerson.
        /// </summary>
        internal static string NameSubreportPackgePerson {
            get {
                return ResourceManager.GetString("NameSubreportPackgePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string NameSubreportPayment {
            get {
                return ResourceManager.GetString("NameSubreportPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportationData.
        /// </summary>
        internal static string NameSubreportTransportationData {
            get {
                return ResourceManager.GetString("NameSubreportTransportationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportationItinerary.
        /// </summary>
        internal static string NameSubreportTransportationItinerary {
            get {
                return ResourceManager.GetString("NameSubreportTransportationItinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportationPerson.
        /// </summary>
        internal static string NameSubreportTransportationPerson {
            get {
                return ResourceManager.GetString("NameSubreportTransportationPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package.
        /// </summary>
        internal static string PackgeTypeFormat {
            get {
                return ResourceManager.GetString("PackgeTypeFormat", resourceCulture);
            }
        }
    }
}
